spring:
  application:
    name: async-transaction-service
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        transactions.delivery: true
        transactions.end.to.end: true
        transactions.queue.wait: true
spring.codec.max-in-memory-size: 16KB
server:
  shutdown: graceful
